##############################
# Dockerfile to run tomcat war
# based off Ubuntu
##############################
FROM ubuntu

#################### SYSTEM DEPENDENCIES #################### 
# Update package list
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils

# Install JVM/JDK, wget, unzip
RUN apt-get -y install default-jdk wget unzip

# Install Gradle
RUN wget "https://downloads.gradle.org/distributions/gradle-4.6-bin.zip"
RUN unzip gradle-4.6-bin.zip
RUN echo "alias gradle=/gradle-4.6-bin/bin/gradle"



#################### RUNTIME DEPENDENCIES #################### 
# Install Tomcat
RUN wget "http://mirrors.ibiblio.org/apache/tomcat/tomcat-9/v9.0.6/bin/apache-tomcat-9.0.6.tar.gz"
RUN echo "export CATALINA_HOME=/apache-tomcat-9.0.6" >> /root/.bashrc
RUN tar -xvf apache-tomcat-9.0.6.tar.gz



#################### CONFIG INJECTION ####################
## WARNING! Insecure password/username
# user/pass
RUN rm /apache-tomcat-9.0.6/conf/tomcat-users.xml
RUN rm /apache-tomcat-9.0.6/webapps/manager/META-INF/context.xml
ADD tomcat-users.xml /apache-tomcat-9.0.6/conf/tomcat-users.xml
ADD context.xml /apache-tomcat-9.0.6/webapps/manager/META-INF/context.xml



#################### CODE INJECTION ####################
ADD * /program/
ADD src /program/src


#################### BUILD PRODUCTS #################### 
RUN cd /program && /gradle-4.6/bin/gradle build && /gradle-4.6/bin/gradle bootwar

RUN ls -aR /program
RUN cp /program/build/libs/program-0.0.1-SNAPSHOT.war /apache-tomcat-9.0.6/webapps/backend.war



#################### Finishing Steps #################### 
# We expose port 8080
EXPOSE 8080

# Entrypoint (Run Tomcat)
ENTRYPOINT /apache-tomcat-9.0.6/bin/catalina.sh run & /bin/bash